spring.datasource.url=jdbc:postgresql://localhost:5432/mathforge
spring.datasource.username=postgres
spring.datasource.password=Carlsen

mathforge.jwt.secret=bXktc3VwZXItc2VjcmV0LWtleS1mb3ItbWF0aGZvcmdlLWFwcC0yMDI0LWxvbmctZW5vdWdo
spring.jpa.hibernate.ddl-auto=update
cloudinary.cloud-name=your-cloud-name
cloudinary.api-key=your-api-key
cloudinary.api-secret=your-api-secret

spring.jpa.show-sql=true
logging.level.com.mathforge=DEBUG
